AllCops:
  NewCops: enable

Lint/ScriptPermission:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9